# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-27 17:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=128)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payMethods', models.CommaSeparatedIntegerField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VendedorAmbulante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superSeller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.Vendedor')),
            ],
        ),
        migrations.CreateModel(
            name='VendedorFijo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_hour', models.TimeField(auto_now=True)),
                ('end_hour', models.TimeField(auto_now=True)),
                ('adress', models.TextField(max_length=128)),
                ('superSeller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.Vendedor')),
            ],
        ),
    ]
