# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 19:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='FixedSeller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_hour', models.TimeField(auto_now=True)),
                ('end_hour', models.TimeField(auto_now=True)),
                ('address', models.TextField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_methods', models.ManyToManyField(to='user.PaymentMethod')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='user.AbstractUser')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorites', models.ManyToManyField(to='user.Seller')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='user.AbstractUser')),
            ],
        ),
        migrations.CreateModel(
            name='WalkingSeller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('super_seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='walking_seller', to='user.Seller')),
            ],
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='vendedorabstracto',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vendedorambulante',
            name='superSeller',
        ),
        migrations.RemoveField(
            model_name='vendedorfijo',
            name='superSeller',
        ),
        migrations.DeleteModel(
            name='Alumno',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='VendedorAbstracto',
        ),
        migrations.DeleteModel(
            name='VendedorAmbulante',
        ),
        migrations.DeleteModel(
            name='VendedorFijo',
        ),
        migrations.AddField(
            model_name='fixedseller',
            name='super_seller',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_seller', to='user.Seller'),
        ),
        migrations.AddField(
            model_name='abstractuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
